### ===================
### HEALTH ENDPOINTS
### ===================

### Health check
GET http://localhost:8080/admin/healthz

### ===================
### CHIRP VALIDATION
### ===================

### Valid chirp
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "This is a short chirp"
}

### Chirp too long
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
}

### Chirp has bad words
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
    "body": "This chirp has kerfuffle sharbert and fornax in it"
}

### Create new chirp
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "Hello, world!",
  "user_id": "123e4567-e89b-12d3-a456-426614174000"
}

### ===================
### ADMIN ENDPOINTS
### ===================

### Reset metrics
POST http://localhost:8080/admin/reset

### Reset users
POST http://localhost:8080/admin/reset

### ===================
### UPDATING USERS
### ===================

### Create user

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "password": "1234",
    "email": "test@newtest.com"
}

### ===================
### USER LOGIN
### ===================

POST http://localhost:8080/api/login
Content-Type: application/json

{
    "password": "1234",
    "email": "test@newtest.com"
}

