### ===================
### HEALTH ENDPOINTS
### ===================

### Health check
GET http://localhost:8080/admin/healthz

### ===================
### CHIRP VALIDATION
### ===================

### Valid chirp
POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "This is a short chirp"
}

### Chirp too long
POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
}

### Chirp has bad words
POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
    "body": "This chirp has kerfuffle sharbert and fornax in it"
}

### ===================
### ADMIN ENDPOINTS
### ===================

### Reset metrics
POST http://localhost:8080/admin/reset